//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourAgency.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> IdTrip { get; set; }
        public Nullable<int> DayCount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> IdTypeTrip { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<int> IdAgent { get; set; }
        public Nullable<bool> IsActual { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Client Client { get; set; }
        public virtual Trip Trip { get; set; }
        public virtual TypeTrip TypeTrip { get; set; }
    }
}
