//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourAgency.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> DayCount { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> IdTypeTrip { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdWay { get; set; }
        public Nullable<int> IdVisa { get; set; }
    
        public virtual TypeTrip TypeTrip { get; set; }
        public virtual Users Users { get; set; }
        public virtual Visa Visa { get; set; }
        public virtual Way Way { get; set; }
    }
}
