//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourAgency.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripImage
    {
        public int Id { get; set; }
        public byte[] Source { get; set; }
        public Nullable<int> IdTrip { get; set; }
    
        public virtual Trip Trip { get; set; }
    }
}
